var stringSimilarity = require("string-similarity");
var tokenizer = require("sbd");

const p = `
! G2 ⌂ Akita Prefecture £
! F1 ⌂ Akita Prefecture
! G1 ⌂ Akita, Aomori, and
As might be expected of a nation consisting of 3,000 islands, Japan is synonymous with the fruits of the sea. Sashimi and sushi have gained popularity with restaurant goers around the world, but it’s hard to imagine some other so-called delicacies catching on. The northern island of Hokkaido boasts of the quality of its uni (sea urchin), while Akita Prefecture is famous for shiokara (raw squid intestines). Domestic tourism and television schedules are dominated by food, and city dwellers travel the length and breadth of the country on weekend excursions to taste regional specialties.
If you plan to travel by rail, get a Japan Rail Pass, which provides unlimited travel on Japan Railways (JR) trains (covering most destinations in Japan) but not on lines owned by other companies. For the Sanyo, Tokaido, and Kyushu Shinkansen lines, the pass is valid on any trains except the Nozomi and Mizuho, which stop infrequently. However, it is valid on all trains on the Yamagata, Tohoku, Joetsu, Akita, and Hokuriku Shinkansen lines.
It would be a hectic rush, but festival freaks could conceivably see all of Tohoku’s big summer festivals in a single whirlwind visit, starting with Hirosaki’s Neputa Matsuri (August 1–7), Aomori’s Nebuta Matsuri (August 2–7), Goshogawara’s Tachi Neputa (August 4–8), Akita’s Kanto Matsuri (August 3–6), Yamagata’s Hanagasa Festival (August 5–7), and the granddaddy of them all, Sendai’s Tanabata Matsuri (August 6–8). Things do get fully booked well ahead (often as early as three to four months), so secure both your train and hotel reservations as soon as you can. Reserved seats on the Shinkansen usually sell out up to a month before the date of travel.
Buses take over where trains do not run, and they usually depart from and return to JR train stations. From Morioka to Hirosaki, highway buses are more convenient (and twice as fast) for getting to Akita than trains. From Tsuruoka to Yamagata, it’s the same story (but it’s a private bus line, not JR, and one of the terminals is in a shopping mall). Note: Overhead space is so severely limited that nothing bigger than a briefcase or handbag will fit. Store your bigger bags below.
The best way to get to Tohoku from Tokyo is on the Tohoku Shinkansen trains, all of which are included in the JR Pass. The fastest Hayabusa run to Aomori, the slower Yamabiko run to Sendai and Morioka, the Tsubasa run to Yamagata, and the Komachi go to Akita. Elsewhere in Tohoku, JR local trains are slower and less frequent (every two hours rather than every hour during the day) when they cross the region’s mountainous spine. Most trains and many buses are owned by Japan Railways, so a JR Rail Pass will be a worthwhile purchase. Be aware that most trains stop running before midnight. Overhead racks are adequate for small packs, but you should stow larger items in spaces at the ends of cars. In Japan no one is ever likely to touch your bags, even if left unattended.
In Sendai, don’t be afraid to try the local delicacy—grilled or braised beef tongue, gyutan, which tastes like a juicy and less chewy version of well-seasoned beef jerky. In Morioka, try the wanko soba challenge—eat as many bowls of cold buckwheat noodles as you can. In Akita, locals are fond of ina-niwa udon noodles that are flatter, whiter, and more tender than the usual udon. In Kakunodate, sakura, or cherry blossoms, are mixed into the flour, and the result is a mildly sweet noodle, as edible as it is pink! Don’t miss the truly unique kiritanpo (hot pot) made with chicken, local vegetables, and distinctive tubular rice cakes that have been formed and cooked onto sticks of bamboo or cedar. Yamagata has its distinctive rounded, chewy soba and incomparable beef. The local sake is uniformly excellent throughout the region, thanks to the quality rice and water.
The Northern Tohoku Tourist Information Center is on the second floor of JR Morioka Station, and the English-speaking staff can give you maps and other information on the three prefectures of Iwate, Akita, and Aomori. The office can also help arrange accommodations with members of a ryokan union.
40 km (25 miles) west of Morioka, 87 km (54 miles) east of Akita.
The highlight is the strong, acidic water (which has a minor amount of radium): gushing out at almost 2,400 gallons per minute, it’s Japan’s swiftest flow from a single spring. In the vicinity is another geothermal area in a national park where many enjoy a hot-rock bath. Take worn-out T-shirts and towels because they will get stained by the waters or even the steam (be careful also of reactive jewelry, such as copper or silver). From JR Tazawa-ko Station in Akita, take the Ugokotsu bus bound for Tamagawa Onsen. The trip takes 75 minutes. | Tazawako Tamagawa | Senboku | 0187/58–3000 | Onsen ¥600, hot rock baths free | Daily 7:30–7:30.
The clear waters and forested slopes of Tazawa-ko, Japan’s deepest lake, create a mystical quality that greatly appeals to the Japanese. According to legend, the great beauty from Akita, Tatsuko Hime, sleeps in the water’s deep, disguised as a dragon. The lake never freezes over in winter because Tatsuko Hime and her dragon husband churn the water with their passionate lovemaking. The less romantic, scientific reason is this: Tazawa-ko has been measured to a depth of 1,397 feet, which prevents it from freezing. Though clear enough to allow you to see a startling 300 feet or more down into it, the mineral-blue water is too acidic to support anything but a few hardy fish.
19 km (12 miles) southwest of Tazawa-ko, 59 km (37 miles) southwest of Morioka, 69 km (43 miles) east of Akita City.
On the JR Komachi Shinkansen Line, Kakunodate can be reached from Tazawa-ko (¥1,390) or Morioka (¥2,640). Akita City is 43 minutes away on the Komachi Shinkansen Line (¥2,820). On local trains, the trip to Akita City takes 90 minutes to two hours because the trains halt at Oomagari Station for a half hour or so.
For walking among the splendid and vast virgin beech, pine, and cedar forests deep in the heart of Tohoku, you could not pick a better destination than Towada-Hachimantai National Park. The mountains afford sweeping panoramas over the park’s gorges and valleys, crystal-clear lakes like Towada-ko, gnarled and windswept trees, and volcanic cones. The park straddles Aomori, Iwate, and Akita prefectures, and sprawls over 330 square miles (855 square km). Hot springs and tiny villages lost in time are secreted here, and the fresh tree-scented air promotes a feeling of true wilderness. | Towada–Hachiman-tai National Park | www.env.go.jp/park/towada.
In the scenic, faraway realm of Akita, the peaks of the Dewa Sanchi (Dewa Range), marked by Mt. Taihei, march off to the east, and the Sea of Japan lies at the edge of the fertile plains that extend to the west. The region’s history began in the year 733, during the turbulent Nara period, with the establishment of Dewa-no-saku, a fortress built on a hill in Takashimizu by the powerful Yamato clan. The area, set up to guard trade routes, soon gained strategic importance, and during the Heian era, soldiers and their families began spreading outward. The Ando and Satake families each built major bastions in the Yuwa and Kawabe districts after the Battle of Sekigahara in 1600. These municipalities, now merged, are considered to be the foundations of modern Akita City. Today the prefectural capital (population 324,000) is a lively, likable city full of delicious food from the mountains, plain, rivers, and sea.
The countryside is devoted to producing what locals feel is the best rice in Japan, and they certainly do make good sake with it. Additionally, the fruits and vegetables grown here are unbelievably cheap and flavorful. The combination of climate, pure water, and healthful food are said to make the women of Akita the fairest in the land—a matter of prefectural, even national, pride. In the Japanese media, “scientific” studies have been trotted out since the 19th century as proof of the Akita bijin (Akita beauty) phenomenon.
ANA and JAL fly to Akita Airport four to five times daily from Tokyo’s Haneda Airport (65 minutes; ¥27,890). JAL also flies twice daily from Osaka’s Itami Airport and three times from Sapporo’s Shin-Chitose Airport. ANA flies twice daily from Nagoya’s Chubu International Airport.
If you’re traveling regionally by rail, the Komachi Shinkansen from Tazawa-ko (one hour; ¥3,360); Tsugaru private line from Aomori City (two hours, 40 minutes; ¥5,600); or the Tsugaru private line from Hirosaki (two hours; ¥4,450) are the most convenient trains. From Tokyo the JR Komachi Shinkansen will spirit you off to Akita in four hours (¥17,800).
By bus, the JR Express bus Dream-Akita departs daily from JR Tokyo Station at 9:50 pm, arriving in JR Akita Station at 6:35 am (¥9,800), while the Willer Express leaves JR Tokyo Station at 10:30 pm, arriving at JR Akita Station at 8:10 am (¥5,500–¥6,400).
The Akita City Tourist Information Center is on the second floor at the station, just across from the exit from the Shinkansen tracks, and supplies many colorful English-language pamphlets and lots of friendly advice.
Akita City Tourist Information Center (Akita-shi Kanko Annaisho). | JR Akita Station 2F, 7–1–2 Naka Dori | 018/832–7941 | www.jnto.go.jp/eng/location/spot/tic/akita_city.html.
If you are not in town for Akita’s famous Kanto Festival, this museum is the next best thing. Try balancing one of the poles topped with paper lanterns on your palm—it’s more difficult than it looks! There is also an informative video about this and other Akita festivals. Your ticket also includes entry to the former residence and kimono fabric shop of the Kaneko family, along a corridor beside the entrance. Don’t miss the bats carved above the sliding doors. | Oomachi 1–3–30, Akita City | 018/866–7091 | ¥100 | Daily 9:30–4:30.
One of the best reasons to visit this new museum is the building, designed by renowned architect Tadao Ando. Sitting in the café, you gaze across a serene pond to the castle moat and park, oblivious of the intervening road. The museum’s other highlight is the enormous Annual Events in Akita, painted by local artist Fujita Tsuguharu (1886–1968) in just 15 days. The painting of three local festivals merged into a single scene was rendered on one of the world’s largest canvases at the time, measuring 11 feet by 66 feet. The museum also hosts temporary exhibitions relating to Akita life and art. From the northwest corner of JR Akita Station, head west on Akita Chuo Dori. After four blocks the museum will be on your left, just before the Castle Hotel. | 1–4–2 Naka Dori | 018/853–8686 | www.akita-museum-of-art.jp | Varies depending on exhibition | Daily 10–6.
Fodor’s Choice | Akita Kawabata Isariya Sakaba.
$$$$ | JAPANESE | This restaurant lives up to its promise of “All of Akita in one building.” Delicious, unique regional dishes, such as the highly recommended pickle selection topped with a tiny paper scarecrow, are served on antique dishes by friendly staff. But the highlight of the evening is the arrival of a namahage, or monster from Akita’s mountains—despite his fearsome appearance, he will happily pose for photographs! On Saturday, there is also a live performance of local folk songs. Look for the namahage statue outside the entrance. | Average main: ¥4000 | 4–2–35 Omachi, Akita | 018/865–8888 | No lunch.
$$$ | HOTEL | Akita Castle Hotel underwent massive renovation in 2012, and now the bright and airy rooms overlooking the moats of Senshu Park are even more comfortable. Ask for rooms on the fifth or sixth floor for better views, and eat breakfast at a window seat in the Japanese restaurant. Azaleas are in full bloom in the park in May and June. For a big splurge, request the Room Imperial, where, as the name indicates, the Imperial Family stays. Pros: good location for sightseeing; nice ambience; good views. Cons: a bit far from the station; impersonal feel. | Rooms from: ¥20000 | 1–3–5 Naka Dori | 018/834–1141 | www.castle-hotel.co.jp | 150 rooms | No meals.
$$$ | HOTEL | The largest hotel in town, the Akita View sits beside the Seibu Department Store. You’re right in the thick of all the shops that line the arcade extending out from the station, and many eateries are located nearby. The hotel’s facilities include a gym and sauna (extra charge), as well as several different dining options. Rooms are simple but adequate. A three-minute walk east brings you to JR Akita Station, and a seven-minute walk takes you to the edge of the entertainment district. Pros: exciting location; good value; delicious, local breakfast. Cons: double rooms on the small side. | Rooms from: ¥19000 | 2–6–1 Naka Dori | 018/832–1111 | www.viewhotels.co.jp/akita | 192 rooms | No meals.
Hotel Metropolitan Akita.
$$$$ | HOTEL | Adjacent to the JR Akita Station and ALS shopping mall, this hotel’s location makes it a perfect choice for shopping and exploring the sights. Rooms are adequate, decorated with wood accents; some deluxe rooms include locally produced crafts and ornaments. Guests can also use a beautiful lounge filled with photography books and local crafts. Children under six years old stay free with their parents. Pros: sleek and modern setting; discount for rail pass holders; elegant lounge. Cons: breakfast room cramped; rooms a little impersonal in style. | Rooms from: ¥23000 | 7–2–1 Naka Dori | 018/831–2222 | www.jrhotelgroup.com/eng/hotel/eng104.htm | 115 rooms | No meals.
132 km (82 miles) south of Akita.
South of Akita along the Nihon-kai coast are small fishing villages where nets hang to dry only inches from train windows, vast plains of rice fields lead to faraway hills, rushing rivers and clear streams are full of fish, and, closer to Atsumi Onsen, you will be confronted with lofty forested mountains coming down to the endless crashing waves. Along the way is the town of Tsuruoka, once a castle stronghold of the Sakai family, which serves as a gateway to Yamagata City and the three mountains of Dewa Sanzan that are held sacred by members of the nature-loving Shugendo sect of “mountain warrior” Buddhists
If you are considering visiting Tsuruoka from Tokyo, the most inexpensive way is by overnight highway bus. Buses leave from various major Tokyo stations between 10 pm and midnight, and arrive in Tsuruoka in the early morning (from ¥4,000). Tsuruoka is 2½ hours south of Akita by JR Uetsu Line (¥2,270). It’s easiest to get to the base of Haguro by bus (35 minutes), either from Bus Stop 2, in front of JR Tsuruoka Station, or from Stop 3, at Sho-Ko (Sho-nai Ko-tsu) Mall (it’s not a JR bus); there are four departures in winter and at least hourly departures in summer. A fare of ¥820 will take you from the station to the Haguro Center village at the entrance to the peak itself. Most buses from Tsuruoka to Haguro Center continue to the summit, Haguro-san-cho, which is not much farther, but the fare jumps to ¥1,180.
The ferries are the cheapest way to travel to Hokkaido on paper, but for roughly the same price you can fly there within two hours from the mainland. Of course, a night on the ferry does save you money on a hotel. If slow travel is your style, there are ferries from Niigata, Akita, Maizuru, and Tsuruga into Otaru, and services on the Pacific side (Nagoya, Oarai, Sendai, Hachinohe, and Aomori) connect to Hakodate or Tomakomai. Other routes include Shin Nihon-kai Ferry’s Niigata to Otaru (18 hours starting at ¥6,480); Taiheiyo Ferry’s Sendai to Tomakomai (14-hour service starting at ¥8,300); Shosen Mitsui’s Oarai to Tomakomai (18 hours from ¥8,740); Taiheiyo Ferry’s mammoth nearly 40-hour Nagoya-Sendai-Tomakomai (¥10,800); Kawasaki Kinkai Kisen’s Hachinohe to Tomakomai (8 hours; ¥5,000); and Seikan Ferry’s service that crosses between Aomori and Hakodate (4 hours; ¥1,690). Aside from winter, the Sea of Japan tends to be calmer than the Pacific. However, if you’re worried about getting seasick, perhaps a plane or a train is a better option.
If you feel like seeing the edge of Japan, walk to Otaru Port and you may see Russian, Chinese, and Korean (North as well as South) ships loaded up with used cars, bicycles, and refrigerators. If you’re interested in boarding a boat yourself, summertime sightseeing boats depart from the dock just beyond the Chuo Bridge for a 25-minute trip to the Herring Mansion area. If you’re ready to leave Hokkaido, there are also ferries to Akita, Niigata, Maizuru, and Tsuruga. | Ironai and Sakaemachi | Otaru.
ATazawako Ski Park Akita Prefecture's largest winter sports destination, Tazawako Ski Park's slopes wind down Akita Komaga-take and overlook the shores of Tazawa-ko. Expect fewer foreigners but a friendly welcome.
Come meet Tokyo's most famous pooch, Hachikō. This Akita dog came to Shibuya Station everyday to meet his master, a professor, returning from work. The professor died in 1925, but Hachikō kept coming to the station until his own death 10 years later. The story became legend and a small statue was erected in the dog’s memory in front of Shibuya Station.
ATōhoku line Runs northeast through Sendai all the way to Aomori, from where you can continue on to Hokkaidō. Branch lines head to Akita and Yamagata.
Tsuruga, south of Fukui and north of Biwa-ko, is a thriving port and train junction. If you've still got a sense of adventure, Shin Nihonkai Ferry Company (%0770-23-2222; www.snf.jp; 2nd class from ¥9300) has nine sailings a week to Tomakomai, Hokkaidō (19½ hours nonstop, 30½ hours with stops). Several of these stop en route at Niigata (¥5200, 12½ hours) and Akita (¥6500, 20 hours). Buses timed to ferry departures serve Tsuruga-kō port from JR Tsuruga Station (¥340, 20 minutes).
The undamaged landscapes of Niigata, Yamagata, Akita and Aomori prefectures are as dramatic and rewarding as ever, home to vibrant festivals and traditions, sensational snow resorts, healing hot springs, mountain hikes along ancient pilgrimage routes, and samurai-era villages.
Further north, the 855-sq-km Towada-Hachimantai National Park (十和田八幡平国立公園) is a vast wilderness area of beech forests, volcanic peaks, crater lakes and alpine plateaus that straddles Akita and Aomori Prefectures.
The Unesco-protected Shirakami-sanchi (白神山地) is a primeval beech forest, also on the Akita–Aomori border. One of the last of its kind in east Asia, it harbours a number of protected species, such as the Asiatic black bear and the golden eagle.
The JR Tōhoku shinkansen (bullet train) line travels as far as Aomori. From there, limited express and local trains run further north to Hokkaidō. The Akita and Yamagata shinkansen branches run through central Tōhoku to the Sea of Japan coast.
The Northern Tōhoku Welcome Card offers discounts on admission, lodging and even transport from participating vendors – identified by a red-and-white Welcome Card sticker – in Iwate, Aomori and Akita Prefectures. Print out the card from the website (www.northern-tohoku.gr.jp/welcome). Note that its use is technically restricted to foreign travellers staying in Japan for less than a year.
If you're driving, the Kan-Etsu Expressway (関越自動車道) runs between Tokyo and the greater Niigata area. The Nihonkai-Tōhoku Expressway (日本海東北自動車道) connects Niigata with Akita.
There are a few tokkyū (limited express trains) each day on the JR Uetsu line between Niigata and Tsuruoka (¥3930, 1¾ hours) and between Niigata and Akita (¥6690, 3¾ hours).
A few daily tokkyū (limited express trains) run on the JR Uetsu main line between Tsuruoka and Akita (¥3610, 1¾ hours) and between Tsuruoka and Niigata (¥3930, 1¾ hours).
Sakata is an easy day trip from Tsuruoka on the local fūtsū train (¥500, 35 minutes) or a pleasant stop en-route to Akita (tokkyū, ¥3280, 1½ hours) on the scenic, coast-hugging Uetsu main-line.
Akita-ken (秋田県) is shaped by the soaring Oū-sanmyaku and Dewa mountain ranges, which have long kept the region isolated. Even today development is divinely sparse. Akita's peaks shelter remote, rustic hot springs that are among the best in the country: paired with neighbouring Lake Tazawa-ko, Nyūtō Onsen is a unique retreat. Civilisation hums along in Akita's fertile valleys, including the prefectural capital of the same name and the feudal city of Kakunodate, a storehouse of samurai culture. The region also claims the most beautiful women in Japan, the so-called Akita-bijin.
The northern terminus of the Akita shinkansen (bullet train), this sprawling commercial city and prefectural capital is one of the region's principal transport hubs. Like most contemporary cities, it was once a castle town, in this case the seat of power of the Satake clan.
6Richmond Hotel Akita Eki-maeB2
7Toyoko Inn Akita-eki Higashi-guchiB2
Originally constructed in 1604, Akita's castle was destroyed with other feudal relics during the Meiji Restoration. The moat still guards the entrance to this leafy park; though hardly sinister, it becomes choked with giant waterlilies in summer. There are also a few pieces of the castle foundation remaining, along with plenty of grassy patches and strolling paths. A reconstruction of a guard tower in the north corner offers views over the city.
Akita's most famous painting, Tsuguharu Fūjita's Events of Akita, is also reputed to be the world's largest canvas painting, measuring 3.65m by 20.5m and depicting traditional Akita life through the seasons. This work and many others are housed in this shiny new Andō Tadao–designed museum with its wonderful public square. Visitors can rest in the 2nd-floor cafe, from where the reflecting pool seems to run directly into Senshū-kōen's moat.
Once the opulent headquarters of Akita Bank, this brick structure built in 1912 is now a folk museum. Inside, you'll find fascinating woodblock prints of traditional Akita life by self-taught artist Katsuhira Tokushi.
At summer's height, Akita celebrates its visually stunning Pole Lantern Festival. As evening falls on the city centre, more than 160 men skilfully balance giant poles, weighing 60kg and hung with illuminated lanterns, on their heads, chins, hips and shoulders, to the beat of taiko drumming groups.
Toyoko Inn Akita-eki Higashi-guchiHOTEL
You can't go past this generic business hotel, adjoining the impressively, recently renovated Akita station, for location and value. It's busy, but staff are friendly and hyper-efficient. Higher floors have nice views.
Richmond Hotel Akita Eki-maeHOTEL
If you're a schnitzel-loving carnivore, you're most likely also a katsu-loving carnivore. If so, you should eat here in this spotless establishment, when you're in Akita. It's adjacent to the station in the Topico building on the 3rd floor. Set meals start at ¥930 and there's a picture menu.
Opposite the shinkansen (bullet train) tracks on the 2nd floor of Akita Station.
From Akita Airport, 21km south of the city centre, flights go to/from Tokyo, Osaka, Nagoya, Sapporo and Seoul. Frequent buses leave for the airport from platform 1 in front of Akita Station (¥920, 40 minutes).
From the port of Akita-kō, Shin Nihonkai (新日本海 %018-880-2600; www.snf.jp) has ferries to Tomakomai on Hokkaidō (from ¥4530, 10 hours), departing at 7am on Tuesday, Wednesday, Friday, Saturday and Sunday. A connecting bus leaves at 6.05am from platform 11 outside Akita Station for Akita-kō (¥440, 30 minutes), 8km northwest of the city.
Highway buses depart from the east exit of the train station, and connect Akita to major cities throughout Honshū.
If you're driving, the Akita Expressway (秋田自動車道) runs east from Akita until it joins with the Tōhoku Expressway. The Nihonkai-Tōhoku Expressway (日本海東北自動車道) runs south along the coast.
The JR Akita shinkansen runs hourly between the northern terminus of Akita and the southern terminus of Tokyo (¥17,460, four hours) via Kakunodate (¥2820, 45 minutes) and Tazawa-ko (¥3160, one hour).
Infrequent local trains also run on the JR Ōu main line between Akita and Kakunodate (¥1320, 1½ hours), with a change at Ōmagari to the JR Tazawako line. There are a few tokkyū (limited express trains) each day on the JR Uetsu line, connecting Akita with Niigata (¥6690, 3¾ hours).
Several of the shinkansen (bullet trains) on the Akita line run hourly between Kakunodate and Tazawa-ko (¥1560, 15 minutes), and between Kakunodate and Akita (¥2940, 45 minutes).
Local trains also run infrequently on the JR Tazawako line between Kakunodate and Tazawa-ko (¥320, 20 minutes), and between Kakunodate and Akita (¥1280, 1½ hours), with a change at Ōmagari to the JR Ōu main line.
If you're driving, Rte 46 connects the Akita Expressway (秋田自動車道) with Tazawa-ko.
The Akita shinkansen runs several times an hour between Tazawa-ko and Tokyo (¥15,830, three hours) and between Tazawa-ko and Akita (¥3160, 55 minutes) via Kakunodate (¥1560, 15 minutes).
According to lore, the onsen became the official bathhouse of Akita's ruling elite after a hunter once saw a crane (tsuru) healing its wounds in the spring. Its milky-white waters are rich in sulphur, sodium, calcium chloride and carbonic acid. The mixed rotemburo is positively jubilant, although shyer folk can take refuge in the indoor gender-segregated baths.
Futsū (local) trains on the JR Ōu main line connect Aomori with Shin-Aomori (¥190, five minutes) and Hirosaki (¥670, 45 minutes). A few JR Tsugaru tokkyū (limited express) trains run daily between Aomori and Akita (¥5080, 2¾ hours) on the same line.
Tokkyū (limited express) trains on the JR Ōu main line run hourly between Aomori and Hirosaki (¥1180, 35 minutes), and Hirosaki and Akita (¥3930, two hours).
Frequent trains run on the JR Akita shinkansen line between Morioka and Akita (¥4620, 1½ hours) via Tazawa-ko (¥2030, 30 minutes) and Kakunodate (¥2840, 50 minutes). The local Tazawa-ko line covers the same route in about twice the time for around half the price; you may need to transfer at Ōmagari.
AShin-Nihonkai Ferry (www.snf.jp) These guys operate down the Japan Sea side of Honshū. Ferries run between Tomakomai, Akita, Niigata and Tsuruga (Fukui-ken); and between Otaru, Niigata and Maizuru (Kyoto-fu).
Shin-Nihonkai Ferry (www.snf.jp) These guys operate down the Japan Sea side of Honshū. Options are between Tomakomai, Akita, Niigata and Tsuruga (Fukui-ken).
Tokushima's main entertainment district is in Akita-machi across the river, along the streets around the landmark ACTY 21 building ( MAP GOOGLE MAP ).
Named after an anime character who always arrives in the nick of time, Kisuke has built a reputation for imaginative seafood dishes. Get a recommendation for the freshest specials by asking, 'Osusume wa arimasu ka?' To find it, take Ryōgoku-bashi south through Akita-machi. Turn left just before the big Kyoei supermarket, and look for Kisuke's striking, modern exterior on the next corner.
Filipina Ingrid is Tokushima's go-to girl for expat gossip and all-night karaoke. The lounge is hard to find, tucked among the hostess clubs in the southwest of Akita-machi, but there's nothing duplicitous about this Tokushima travellers' institution. Beware: Ingrid never forgets a face!
JR East Pass The JR East Pass (www.jreast.co.jp/e/eastpass) is a great deal for those who only want to travel in eastern Japan. The passes are good on all JR lines in eastern Japan (including Tōhoku, Yamagata, Akita, Jōetsu and Nagano shinkansen, but not including the Tōkaidō shinkansen). This includes the area around Tokyo and everything north of Tokyo to the tip of Honshū, but doesn't include Hokkaidō. The passes are good for travel on any five days of a 14-day period that starts with purchase or activation of the pass in Japan. The travel dates do not have to be declared in advance. The passes cost ¥22,000/11,000 per adult/child. The passes are only good for travel in ordinary cars (ie there are no Green Car passes). Unlike the Japan Rail Pass, the pass can be purchased inside Japan (by those holding tourist visas), as well as outside Japan. The passes can also be purchased online.
`.replace(/,+/g, ",");

const nameAry =
  // p
  //   .split("\n")
  tokenizer.sentences(p.replace(";", "."), { sanitize: true }).filter(Boolean);
// .filter((x) => x.includes("cancun") || x.includes("Cancún"));
//   .sort(() => 0.5 - Math.random())
//   .slice(0, 14);

const sorted = nameAry
  .sort(
    (a, b) =>
      stringSimilarity.compareTwoStrings(nameAry[0], a) -
      stringSimilarity.compareTwoStrings(nameAry[0], b)
  )
  .sort(
    (a, b) =>
      stringSimilarity.compareTwoStrings(nameAry[10], a) -
      stringSimilarity.compareTwoStrings(nameAry[10], b)
  );

// console.log(stringSimilarity.findBestMatch(nameAry[0], nameAry));
sorted.forEach((line) => {
  console.log(line + "\n");
});
